name: "Check PR"

on:
  pull_request:


jobs:
  terraform-fmt:
    name: "Terraform fmt"
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: 'terraform'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Tell the user that fmt failed
        id: fmt-check
        run: echo "terraform fmt failed, please make sure your .tf files are properly formatted before committing."; exit 1
        if: ${{ steps.fmt.outcome == 'failure' }}

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ${{ env.tf_actions_working_dir }}/pr/
